"""Casos de uso e portas; sem detalhes de framework."""

from caleo_transcriber.application.api_key_settings import (
    OPENAI_CREDENTIAL_ACCOUNT,
    OPENAI_CREDENTIAL_SERVICE,
    ApiKeySettings,
    LocalKeyValidation,
)
from caleo_transcriber.application.batch import (
    BatchAddResult,
    BatchEvents,
    BatchProcessor,
    BatchQueueEvent,
    BatchSettings,
    LongMediaUseCase,
)
from caleo_transcriber.application.checkpoints import (
    CheckpointChunk,
    CheckpointStore,
    ChunkCheckpointState,
    LongMediaCheckpoint,
)
from caleo_transcriber.application.credentials import (
    CredentialStore,
    CredentialStoreError,
    CredentialStoreFailure,
    SecretValue,
)
from caleo_transcriber.application.media import (
    AudioChunkExtractor,
    AudioExtractor,
    MediaError,
    MediaFailure,
    MediaInfo,
    MediaProbe,
    PreparedAudio,
    PreparedAudioLease,
    SilenceDetector,
)
from caleo_transcriber.application.output import (
    OutputFormat,
    OutputWriteCancelled,
    OutputWriteError,
    TranscriptOutputWriter,
    TxtOutputWriter,
)
from caleo_transcriber.application.transcribe_long_media import (
    TranscribeLongMedia,
    TranscribeLongMediaCommand,
)
from caleo_transcriber.application.transcribe_single_file import (
    AttemptEvent,
    AttemptEvents,
    AttemptFailure,
    TranscribeSingleFile,
    TranscribeSingleFileCommand,
    TranscribeSingleFileFailure,
    TranscribeSingleFileResult,
    TranscribeSingleFileSuccess,
    TranscribeSingleFileUseCase,
    TranscriptionAlreadyRunningError,
)
from caleo_transcriber.application.transcription import (
    ProviderFailure,
    TranscriptionFailure,
    TranscriptionProvider,
    TranscriptionRequest,
    TranscriptionResult,
    TranscriptionSegment,
    TranscriptionSuccess,
)

__all__ = [
    "BatchAddResult",
    "BatchEvents",
    "BatchProcessor",
    "BatchQueueEvent",
    "BatchSettings",
    "LongMediaUseCase",
    "CheckpointChunk",
    "CheckpointStore",
    "ChunkCheckpointState",
    "LongMediaCheckpoint",
    "CredentialStore",
    "CredentialStoreError",
    "CredentialStoreFailure",
    "SecretValue",
    "ApiKeySettings",
    "LocalKeyValidation",
    "OPENAI_CREDENTIAL_ACCOUNT",
    "OPENAI_CREDENTIAL_SERVICE",
    "OutputWriteCancelled",
    "OutputWriteError",
    "OutputFormat",
    "TranscriptOutputWriter",
    "TxtOutputWriter",
    "AudioExtractor",
    "AudioChunkExtractor",
    "MediaError",
    "MediaFailure",
    "MediaInfo",
    "MediaProbe",
    "PreparedAudio",
    "PreparedAudioLease",
    "SilenceDetector",
    "ProviderFailure",
    "TranscriptionFailure",
    "TranscriptionProvider",
    "TranscriptionRequest",
    "TranscriptionResult",
    "TranscriptionSegment",
    "TranscriptionSuccess",
    "AttemptEvent",
    "AttemptEvents",
    "AttemptFailure",
    "TranscribeSingleFile",
    "TranscribeSingleFileCommand",
    "TranscribeSingleFileFailure",
    "TranscribeSingleFileResult",
    "TranscribeSingleFileSuccess",
    "TranscribeSingleFileUseCase",
    "TranscriptionAlreadyRunningError",
    "TranscribeLongMedia",
    "TranscribeLongMediaCommand",
]
